// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddableItemKind } from "./AddableItemKind";
import type { CatalogItemId } from "./CatalogItemId";

/**
 * A catalog-backed item constructor. The opaque id is the only value the
 * frontend may submit when requesting a new saved stack.
 */
export type AddableItemView = { id: CatalogItemId, itemId: string, name: string, kind: AddableItemKind, cargoSpacePerUnit: string, maxQuantity: string, localResourcesEligible: boolean, };
