// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupId } from "./BackupId";
import type { SaveId } from "./SaveId";

export type ApplyResult = { saveId: SaveId, backupId: BackupId | null, targetPath: string, campaignHash: string, descriptorHash: string, message: string, };
