// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplyMode = { "type": "replace_original" } | { "type": "save_copy", targetRoot: string, };
