// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupId } from "./BackupId";
import type { SaveId } from "./SaveId";

export type BackupSummary = { id: BackupId, saveId: SaveId, createdAt: string, reason: string, sizeBytes: string, gameVersion: string, pinned: boolean, };
