// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddableItemView } from "./AddableItemView";
import type { PortraitView } from "./PortraitView";

export type CatalogView = { portraits: Array<PortraitView>, addableItems: Array<AddableItemView>, };
