// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortraitId } from "./PortraitId";
import type { SkillView } from "./SkillView";

export type CharacterView = { firstName: string, lastName: string, portraitId: PortraitId | null, portraitPath: string, 
/**
 * Decimal text validated and rounded by the backend as a finite Java float.
 */
credits: string, level: number, 
/**
 * Decimal string to avoid JavaScript integer precision loss.
 */
xp: string, skillPoints: number, storyPoints: number, skills: Array<SkillView>, };
