// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColonyId } from "./ColonyId";
import type { ColonyResourcesView } from "./ColonyResourcesView";
import type { StorageView } from "./StorageView";

export type ColonyView = { id: ColonyId, name: string, locationContext: string | null, storage: StorageView | null, localResources: ColonyResourcesView | null, warnings: Array<string>, };
