// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColonyResourceStackView } from "./ColonyResourceStackView";

export type ColonyResourcesView = { stacks: Array<ColonyResourceStackView>, usedSpace: string, maxSpace: string | null, overloaded: boolean, editable: boolean, reason: string | null, };
