// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Diagnostics = { appVersion: string, os: string, 
/**
 * Redacted operational events only; save content and full paths are excluded.
 */
entries: Array<string>, };
