// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationInfo } from "./InstallationInfo";
import type { SaveRoot } from "./SaveRoot";

export type DiscoveryResult = { installations: Array<InstallationInfo>, registeredRoots: Array<SaveRoot>, };
