// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogItemId } from "./CatalogItemId";
import type { ColonyId } from "./ColonyId";
import type { ColonyResourceStackId } from "./ColonyResourceStackId";
import type { InventoryStackId } from "./InventoryStackId";
import type { OfficerId } from "./OfficerId";
import type { PortraitId } from "./PortraitId";
import type { StorageStackId } from "./StorageStackId";

/**
 * The only semantic changes accepted across IPC. Raw XML/XPath edits are intentionally absent.
 */
export type Edit = { "type": "set_player_name", firstName: string, lastName: string, } | { "type": "set_player_portrait", portraitId: PortraitId, } | { "type": "set_credits", value: string, } | { "type": "grant_player_xp", amount: string, } | { "type": "raise_player_to_level", level: number, } | { "type": "set_player_points", skillPoints: number, storyPoints: number, } | { "type": "set_player_skill", skillId: string, rank: number, } | { "type": "set_relation", factionId: string, value: number, } | { "type": "grant_officer_xp", officerId: OfficerId, amount: string, } | { "type": "raise_officer_to_level", officerId: OfficerId, level: number, } | { "type": "set_officer_points", officerId: OfficerId, skillPoints: number, } | { "type": "set_officer_skill", officerId: OfficerId, skillId: string, rank: number, } | { "type": "set_inventory_quantity", stackId: InventoryStackId, quantity: string, } | { "type": "set_storage_stack_quantity", colonyId: ColonyId, stackId: StorageStackId, quantity: string, } | { "type": "set_colony_resource_quantity", colonyId: ColonyId, stackId: ColonyResourceStackId, quantity: string, } | { "type": "add_storage_item", colonyId: ColonyId, catalogItemId: CatalogItemId, quantity: string, } | { "type": "add_colony_resource", colonyId: ColonyId, catalogItemId: CatalogItemId, quantity: string, };
