// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "UNSUPPORTED_VERSION" | "UNSUPPORTED_COMPRESSION" | "AMBIGUOUS_STRUCTURE" | "STALE_SAVE" | "GAME_RUNNING" | "VALIDATION_FAILED" | "RECOVERY_REQUIRED" | "INVALID_ARGUMENT" | "NOT_FOUND" | "PERMISSION_DENIED" | "PROTECTED_SAVE" | "REVIEW_CONSUMED" | "IO_ERROR" | "INTERNAL_ERROR";
