// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettingsProfileId } from "./GameSettingsProfileId";
import type { GameSettingsValues } from "./GameSettingsValues";

export type GameSettingsProfile = { profileId: GameSettingsProfileId, name: string, values: GameSettingsValues, builtIn: boolean, };
