// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettingsSnapshot } from "./GameSettingsSnapshot";

export type GameSettingsApplyResult = { snapshot: GameSettingsSnapshot, backupId: string, message: string, };
