// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettingsValues } from "./GameSettingsValues";
import type { InstallationId } from "./InstallationId";

export type GameSettingsSnapshot = { installationId: InstallationId, displayName: string, displayPath: string, values: GameSettingsValues, revision: string, writable: boolean, };
