// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationId } from "./InstallationId";

export type InstallationInfo = { installationId: InstallationId, displayName: string, displayPath: string, detectedVersion: string | null, savesRootAvailable: boolean, };
