// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryKind } from "./InventoryKind";
import type { InventoryStackId } from "./InventoryStackId";

export type InventoryStackView = { id: InventoryStackId, itemId: string, specialData: string | null, name: string, kind: InventoryKind, 
/**
 * Decimal text rounded and validated by the backend as a finite Java float.
 */
quantity: string, 
/**
 * The maximum size already stored on this existing stack.
 */
maxQuantity: string, cargoSpacePerUnit: string, editable: boolean, reason: string | null, };
