// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryStackView } from "./InventoryStackView";

export type InventoryView = { stacks: Array<InventoryStackView>, usedSpace: string, maxSpace: string | null, overloaded: boolean, editable: boolean, reason: string | null, };
