// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficerId } from "./OfficerId";
import type { SkillView } from "./SkillView";

export type OfficerView = { id: OfficerId, name: string, portraitPath: string | null, personality: string, assignment: string | null, level: number, xp: string, skillPoints: number, skills: Array<SkillView>, progressionEditable: boolean, progressionReason: string | null, };
