// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortraitId } from "./PortraitId";

export type PortraitView = { id: PortraitId, relativePath: string, label: string, };
