// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveId } from "./SaveId";

export type RecoveryItem = { transactionId: string, saveId: SaveId | null, summary: string, lastCompletedPhase: string, };
