// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryItem } from "./RecoveryItem";
import type { RecoveryStatus } from "./RecoveryStatus";

export type RecoveryState = { status: RecoveryStatus, items: Array<RecoveryItem>, };
