// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSection } from "./ReviewSection";

export type ReviewChange = { key: string, section: ReviewSection, label: string, before: string, after: string, derived: boolean | null, };
