// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewChange } from "./ReviewChange";
import type { ReviewId } from "./ReviewId";
import type { ReviewWarning } from "./ReviewWarning";

export type Review = { reviewId: ReviewId, revision: string, changes: Array<ReviewChange>, warnings: Array<ReviewWarning>, errors: Array<string>, canApply: boolean, };
