// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogView } from "./CatalogView";
import type { CharacterView } from "./CharacterView";
import type { ColonyView } from "./ColonyView";
import type { FieldCapability } from "./FieldCapability";
import type { InventoryView } from "./InventoryView";
import type { OfficerView } from "./OfficerView";
import type { RelationView } from "./RelationView";
import type { SaveId } from "./SaveId";
import type { SaveSummary } from "./SaveSummary";
import type { SessionId } from "./SessionId";

export type SaveSnapshot = { sessionId: SessionId, saveId: SaveId, 
/**
 * Opaque digest of both source files; never XML or patch coordinates.
 */
revision: string, summary: SaveSummary, protectedLocked: boolean, writeCapability: FieldCapability, progressionCapability: FieldCapability, character: CharacterView, relations: Array<RelationView>, officers: Array<OfficerView>, inventory: InventoryView | null, colonies: Array<ColonyView>, catalog: CatalogView, warnings: Array<string>, };
