// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootId } from "./RootId";

export type SaveRoot = { rootId: RootId, displayName: string, displayPath: string, available: boolean, writable: boolean, };
