// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatibilityState } from "./CompatibilityState";
import type { RootId } from "./RootId";
import type { SaveId } from "./SaveId";

export type SaveSummary = { id: SaveId, rootId: RootId | null, 
/**
 * Display-only path. It cannot be fed to any command except explicit root registration.
 */
path: string, characterName: string, characterLevel: number, gameVersion: string, saveFileVersion: string, saveDate: string, location: string, ironMode: boolean, autosave: boolean, compressed: boolean, enabledMods: Array<string>, compatibility: CompatibilityState, compatibilityReason: string | null, };
