// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillView = { id: string, name: string, group: string, rank: number, maxRank: number, editable: boolean, reason: string | null, iconId: string | null, };
