// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageStackView } from "./StorageStackView";

export type StorageView = { stacks: Array<StorageStackView>, usedSpace: string, maxSpace: string | null, overloaded: boolean, editable: boolean, reason: string | null, };
