// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryKind } from "./InventoryKind";
import type { StorageStackId } from "./StorageStackId";

export type StorageStackView = { id: StorageStackId, itemId: string, specialData: string | null, name: string, kind: InventoryKind, quantity: string, maxQuantity: string, cargoSpacePerUnit: string, editable: boolean, reason: string | null, };
